.travis.yml, package.json, yarn.lock
=> chore: enable travis builds

docs/cli.md, docs/getting-started.md, packages/cli/src/collect/collect.js
well i started writing out #49 but then  figured id just try out the changes myself. :)
hope you dont hate these!
=> revise getting started and cli docs

packages/server/src/ui/routes/project-dashboard/project-graphs.jsx
this screenshot is more than twenty but i think its quite a lovely overview.
=> more dots in the overview graph

docs/getting-started.md
Link to correct document location
=> Update autorun document location

packages/cli/README.md
Add readme for the core `npm` package.  Probably worth doing for the other two, too, but this is a start.
=> Add README for @lhci/cli package

README.md
closes #68 
Now LHCI has it's own related projects section 🎉 
@patrickhulce, let's get party started 💃
=> docs: related projects section with GitHub Action

docs/getting-started.md
Working Example: https://github.com/HugoGresse/open-feedback/runs/302616724
CLA Signed: ☑
=> Docs: add Github Actions to getting started doc

packages/server/README.md
=> Add README for @lhci/server package

packages/utils/README.md
Create README for @lhci/utils.
=> Create README for utils package

docs/getting-started.md
I'm not sure if I'm the right guy to add the second part notice though it's written [here](https://github.com/GoogleChrome/lighthouse-ci/issues/74#issuecomment-554023063) 😁
=> Docs: Add note to Temporary Storage Server for diffing

docs/getting-started.md
=> Docs: fix broken link in getting-started

docs/cli.md
Fixes the broken link to assertions.md in cli.md
=> docs(cli): fixed link to assertions.md

README.md
closes https://github.com/GoogleChrome/lighthouse-ci/issues/106
=> add my repo to "related projects" section

packages/server/src/ui/components/async-loader.jsx, packages/server/src/ui/components/loading-spinner.css, packages/server/src/ui/components/loading-spinner.jsx, packages/server/src/ui/components/loading-spinner.svg, packages/server/src/ui/hooks/use-api-data.jsx, packages/server/src/ui/routes/project-dashboard/project-graphs.jsx, packages/server/test/ui/components/async-loader.test.jsx
=> fix(server): remove 404 case when no master builds exist

docs/getting-started.md, packages/cli/src/upload/upload.js, packages/server/src/server.js, packages/utils/src/build-context.js, packages/utils/test/build-context.test.js
=> feat(utils): add support for gitlab build context + manual overrides

docs/cli.md
Hi,
I added configs for [yarn](https://yarnpkg.com)
Cheers 👋,
Vitalii
=> docs(cli): add yarn installation example

packages/cli/test/test-utils.js, packages/utils/src/saved-reports.js, packages/utils/test/saved-reports.test.js
=> feat(cli): write HTML reports to .lighthouseci too

packages/cli/src/collect/collect.js, packages/cli/test/collect-puppeteer.test.js
- add checkIgnoredChromeFlagsOption function
- add test code for checkIgnoredChromeFlagsOption function
closes #143
=> feat(cli): Add warning when using chrome-flags and puppeteerScript

packages/server/src/ui/app.css, packages/server/src/ui/layout/page-sidebar.css, packages/server/src/ui/layout/page-sidebar.jsx
@patrickhulce I am raising this PR to address #145. 
Below is a quick overview of what has changed:
1.  I am making use of process.env.npm_package_version to make this change at the build time. I assume the `lerna version` lifecycle scripts will update the package.json  and the same will be picked by `parcel` in the `build` command.
2. JSX Changes in page-sidebar.jsx to add the siderbar footer and version elements. 
3. CSS changes in app.css and page-sidebar.css
Attaching few screenshots for your reference.
=> Show package version in server UI sidebar

.github/semantic.yml
=> feat: add semantic-pull-request support

docs/cli.md, packages/cli/src/assert/assert.js, packages/cli/test/assert.test.js, packages/utils/src/assertions.js, packages/utils/test/assertions.test.js, types/assert.d.ts
=> feat(cli): add includePassedAssertions flag

.dependabot/config.yml
=> chore: add dependabot configuration file

packages/server/src/ui/app.css, packages/server/src/ui/hooks/use-api-data.jsx, packages/server/src/ui/routes/project-dashboard-redesign/build-list.css, packages/server/src/ui/routes/project-dashboard-redesign/build-list.jsx, packages/server/src/ui/routes/project-dashboard-redesign/category-card.jsx, packages/server/src/ui/routes/project-dashboard-redesign/graphs/donut-graph.css, packages/server/src/ui/routes/project-dashboard-redesign/graphs/donut-graph.jsx, packages/server/src/ui/routes/project-dashboard-redesign/project-dashboard.css, packages/server/src/ui/routes/project-dashboard-redesign/project-dashboard.jsx, packages/server/test/server-test-suite.js, types/server.d.ts
ref #179 
closes #214 
@Zizzamia this one's for you :)
=> Paginated and filterable build table

docs/troubleshooting.md, packages/cli/src/collect/collect.js, packages/cli/src/collect/puppeteer-manager.js
=> feat(cli): fallback to puppeteer-core when puppeteer missing

.travis.yml, packages/cli/src/upload/upload.js, scripts/ci-dogfood.sh
=> Add GitHub App to Dogfood

lighthouserc.json, packages/server/src/ui/index.html, packages/server/src/ui/layout/page-sidebar.jsx, packages/server/src/ui/routes/project-dashboard-redesign/graphs/donut-graph.jsx, packages/viewer/src/ui/index.html, scripts/ci-dogfood-get-urls.js
=> fix(server): minor a11y fixes

packages/cli/src/upload/upload.js, packages/cli/test/upload.test.js, types/upload.d.ts
=> feat(cli): ignoreDuplicateBuildFailures

packages/cli/src/collect/collect.js, types/collect.d.ts
closes https://github.com/GoogleChrome/lighthouse-ci/issues/243
=> feat(cli): add startServerReadyTimeout option

packages/cli/src/upload/upload.js, scripts/ci-dogfood.sh, types/upload.d.ts
fixes https://github.com/GoogleChrome/lighthouse-ci/pull/230#issuecomment-601493415
=> fix(cli): revert to `lhci` github status context

packages/server/src/ui/app.jsx, packages/server/src/ui/hooks/use-api-data.jsx, packages/server/src/ui/layout/page-sidebar.css, packages/server/src/ui/layout/page-sidebar.jsx, packages/server/src/ui/routes/project-settings/project-settings.css, packages/server/src/ui/routes/project-settings/project-settings.jsx
super simple administrative settings page for managing projects, a place for future settigns like branch configuration to go in the future
closes #85
=> feat(server): add project settings page for deletion

packages/server/src/ui/routes/build-view/lhr-comparison.jsx
=> feat(server): add audit permalinks to lhr comparison

packages/cli/test/cli.test.js, packages/server/src/ui/components/async-loader.jsx, packages/server/src/ui/routes/project-dashboard-redesign/category-card.jsx, packages/server/test/ui/components/async-loader.test.jsx
=> fix(server): use friendly error message for statistic computation

packages/cli/src/wizard/wizard.js
=> fix(cli): out-of-date message for wizard instead of undefined token

docs/configuration.md
I stumbled on this while testing out Katie's web.dev guide (which will go out this month 😄)
=> Add an example of a custom build directory

README.md, docs/configuration.md, docs/getting-started.md, docs/recipes/docker-server/README.md, docs/recipes/heroku-server/README.md, docs/server.md, packages/server/README.md
=> docs(server): more comprehensive server documentation

packages/server/src/ui/hooks/use-api-data.jsx, packages/server/src/ui/layout/page-sidebar.jsx
=> fix(server): pull version from server API

packages/cli/src/utils.js, packages/cli/src/wizard/wizard.js, packages/cli/test/wizard.test.js, packages/server/src/api/storage/sql/sql.js, packages/server/src/api/storage/storage-method.js, packages/utils/src/api-client.js
=> feat(cli): add reset-project-token wizard

packages/cli/test/test-utils.js
to test.. add:
```js
throw new Error('Please install sqlite3 package manually');
```
to `node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:20`
and run `yarn jest -i wizard`
=> tests: log unexpected server close

README.md
Fixes the image url for one of the screenshots in the readme file.
=> Update README Screenshot URL

packages/server/src/api/storage/sql/sql.js, packages/server/test/server-test-suite.js
=> fix(server): avoid double prefixing 0 for buildId lookup

packages/cli/src/upload/upload.js, packages/cli/test/upload.test.js, packages/server/src/api/storage/sql/sql.js
=> fix(cli): truncate run URL before upload

README.md, docs/complex-setup.md, docs/configuration.md, docs/getting-started.md, docs/migration-guide.md, docs/recipes/heroku-server/package.json, docs/version-policy.md, packages/cli/src/collect/puppeteer-manager.js, packages/server/src/api/storage/auth.js
=> Update docs for 0.4.0

docs/configuration.md, packages/cli/src/autorun/autorun.js, types/autorun.d.ts
=> feat(cli): add failOnUploadFailure autorun option

packages/cli/src/collect/collect.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/fixtures/puppeteer/auth-server.js
fixes https://github.com/GoogleChrome/lighthouse-ci/pull/282#issuecomment-636034831
...again
=> fix(cli): pass chromePath through to runner

docs/getting-started.md
Add instructions on how to use the wizard behind basic auth
=> Basic auth instructions

.github/workflows/ci.yml, .travis.yml, packages/cli/test/cli.test.js, packages/cli/test/collect.test.js, packages/cli/test/test-utils.js, packages/cli/test/upload.test.js, packages/server/test/test-utils.js, packages/server/test/ui/storybook.test.jsx, packages/utils/src/build-context.js, packages/utils/test/build-context.test.js
trying this again afterall because 75% failure rate on screenshots without the ability to save artifacts is 😠
=> chore: switch to GitHub actions

packages/cli/test/cli.test.js, packages/utils/src/api-client.js, packages/utils/test/api-client.test.js
follow up to #353 with the functionality to make it happen
=> fix(cli): respect path of serverBaseUrl

docs/configuration.md
Fixes #361
I still think there's more nuance to this script stuff, but hopefully this covers in more detail?
Preview: https://github.com/GoogleChrome/lighthouse-ci/pull/367/files?short_path=76e7313#diff-76e731333fb756df3bff5ddb3b731c46
=> Clarify puppeteer docs

CONTRIBUTING.md
ref https://github.com/GoogleChrome/lighthouse-ci/issues/338#issuecomment-650016709
=> docs(CONTRIBUTING): add codebase explainer

packages/cli/src/upload/upload.js, types/upload.d.ts
=> feat(cli): allow status app url to be configured

README.md
=> add to readme for CONTRIBUTING.md link

.github/workflows/ci.yml
Landing at least the postgres socket test so we have *some* coverage to make sure socket options are working
=> tests: add postgresql socket test to CI

.github/workflows/ci.yml, packages/cli/src/healthcheck/healthcheck.js
fixes https://github.com/GoogleChrome/lighthouse-ci/issues/414
=> fix(cli): do not require chrome for PSI collect

packages/server/src/api/storage/sql/migrations/2020081801-table-indexes.js
closes #410 
**Before**
**After**
=> feat(server): add indexes on common queries

packages/cli/src/assert/assert.js, packages/utils/src/assertions.js, packages/utils/test/assertions.test.js
=> fix(cli): add message for misconfigured audit assertions

docs/troubleshooting.md
Fix broken link in troubleshooting.md
=> Fix broken link in troubleshooting.md

.github/workflows/ci.yml, packages/server/src/cron/delete-old-builds.js, packages/server/src/ui/routes/build-view/audit-list/numeric-diff.jsx, packages/server/src/ui/routes/build-view/build-view.jsx, packages/server/test/cron/delete-old-builds.test.js, packages/utils/src/api-client.js, packages/utils/src/assertions.js
=> fix(server): improved CLS comparisons in diff view

README.md, docs/getting-started.md
Hello! 👋🏼 
Yesterday I was migrating from Travis-CI to GitHub Actions and I found a couple of things that are not mentioned on the docs that could be helpful to include
=> docs: Improve GitHub Actions snippets

packages/cli/src/cli.js, packages/cli/src/healthcheck/healthcheck.js, packages/cli/src/upload/upload.js, packages/cli/test/assert.test.js, packages/cli/test/collect-static-dir.test.js, packages/cli/test/collect.test.js, packages/cli/test/upload.test.js, packages/utils/src/build-context.js, packages/utils/test/build-context.test.js
=> Fix CLI getAncestorBranch and nested environment variables

docs/configuration.md
This PR is adding document of deleteOldBuildsCron
Ref: https://github.com/GoogleChrome/lighthouse-ci/pull/471#issuecomment-731609275
=> docs: add deleteOldBuildsCron

packages/cli/package.json, yarn.lock
- Bumped yargs-parser@13.1.2 for security advisory https://github.com/advisories/GHSA-p9pc-299p-vxgp
=> bump: yargs, yargs-parser

package.json, packages/cli/package.json, packages/cli/src/healthcheck/healthcheck.js, packages/server/package.json, packages/server/src/api/storage/sql/sql.js, packages/server/src/api/storage/storage-method.js, packages/utils/package.json, packages/utils/src/api-client.js, yarn.lock
**Usage**
```bash
DEBUG=lhci:*,-*:verbose lhci server
DEBUG=lhci:* lhci healthcheck
```
ref #533
closes #522
=> feat: improved debug logging

packages/cli/package.json, packages/utils/package.json, yarn.lock
Fixes #580 (severe vulnerability fix) by updating lighthouse version from 7.0.0 to 7.3.0
=> Update lighthouse to v7.3.0

.github/workflows/ci.yml, docs/recipes/docker-client/test-in-container.sh, docs/recipes/docker-client/test.sh, docs/recipes/docker-server/test-in-container.sh, docs/recipes/docker-server/test.sh, package.json, scripts/test-docker.sh
=> tests: add basic docker tests

packages/server/src/ui/routes/build-view/build-view.jsx, packages/server/src/ui/routes/project-dashboard/project-dashboard.jsx
Some of the URLs I'm using are in Chinese, which currently display urlencoded and are therefore hard to differentiate. This just decodes them for display (similar to the address bar).
=> Decode URL's for display

README.md
Add my Lighthouse articles to "Community Guides" section
=> Update README.md to add 2 additional articles under "Community Guides" section

packages/utils/src/api-client.js, packages/utils/test/api-client.test.js
=> fix(utils): throw on non-200 version response

docs/getting-started.md
Cloud Build (as see in https://cloud.google.com/build)
=> Use proper capitalization for Cloud Build

package.json, packages/cli/package.json, packages/cli/src/cli.js, yarn.lock
This is a continuation of https://github.com/GoogleChrome/lighthouse/pull/13588
=> chore(deps): remove update-notifier

docs/configuration.md
=> docs: clarify when Github status checks apply

docs/recipes/docker-client/Dockerfile, docs/recipes/docker-server/Dockerfile
=> chore: bump to node 16 in dockerfiles

docs/recipes/heroku-server/README.md, docs/server.md
Heroku no longer offers a free tier
=> Update Heroku server README.md

docs/configuration.md
Part of https://github.com/GoogleChrome/lighthouse-ci/issues/973
=> docs: add *.cjs to supported config extensions
