packages/server/src/ui/routes/build-view/build-hash-selector.jsx
7 characters is the typical short length (used in github and travis)
admittedly, git uses 9 these days with --short but I think its nicer to use the short one, and to align with github & travis.
=> git short hash of 7

package.json, packages/cli/src/autorun/autorun.js, packages/cli/test/assert.test.js, packages/utils/src/lighthouserc.js, packages/utils/test/lighthouserc.test.js, types/lighthouserc.d.ts, yarn.lock
The last remaining item in #48, `ci:client`/`ci:server` support.
closes #48
=> feat(utils): support ci:client/ci:server rc properties

packages/cli/src/assert/assert.js, packages/cli/test/cli.test.js, packages/utils/src/budgets-converter.js, packages/utils/test/assertions.test.js, packages/utils/test/budgets-converter.test.js
Howdy 👋 
Some of the users are running into an issues when failed assertion results for `resource-summary` are inconsistent with budget (for example - https://github.com/treosh/lighthouse-ci-action/issues/13)
E.g. I setup budget for 1KB, actual value is ~17KB. 
What seen in console is something like that:
```
expected: <=1
found: 17387
```
For better UX, I propose smth like we have in LH
```
expected: <=1.00 KB
found: 16.98 KB
```
Here is comparison of logs before and after the proposal:
P.R. Is still draft, if we are ok, I can tune more stuff for that. 
Cheers,
=> fix(cli): resource-summary output and budget

packages/cli/package.json, packages/cli/src/healthcheck/healthcheck.js, packages/cli/test/autorun-start-server.test.js, packages/cli/test/autorun-static-dir.test.js, packages/cli/test/cli.test.js, packages/cli/test/healthcheck.test.js, yarn.lock
common issue is that chrome isn't available on their instance, this adds the check to `healthcheck` to catch it earlier and print a nice message
=> feat(cli): add chrome installations to healthcheck

docs/cli.md, docs/recipes/docker-server/update-dockerhub.sh, docs/troubleshooting.md, packages/cli/src/collect/collect.js, packages/cli/src/collect/lighthouse-runner.js, packages/cli/src/collect/puppeteer-manager.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/fixtures/puppeteer/auth-server-script.js, packages/cli/test/fixtures/puppeteer/auth-server.js, types/collect.d.ts
closes #89 
Usage looks like:
```
lhci collect \
--start-server-command="yarn serve" \
--url=http://localhost:8080/ \
--puppeteer-script=./path/to/login-with-puppeteer.js
```
**Example `login-with-puppeteer.js`**
```js
/**
* @param {puppeteer.Browser} browser
* @param {{url: string, options: LHCI.CollectOptions}} context
*/
module.exports = async (browser, context) => {
const page = await browser.newPage();
await page.goto('http://localhost:8080/login');
await page.type('#username', 'admin');
await page.type('#password', 'password');
await page.click('[type="submit"]');
await page.waitForNavigation();
};
```
=> feat(cli): add --puppeteer-script flag to collect

docs/cli.md, packages/cli/src/collect/collect.js, packages/cli/src/collect/puppeteer-manager.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/fixtures/puppeteer/auth-server.js, types/collect.d.ts
example usage:
```json5
{
"ci": {
"collect": {
"puppteerLaunchOptions": {"args": ["--no-sandbox", "--disable-gpu"]}
}
}
}
```
closes #132
closes #133
=> feat(cli): add --puppeteer-launch-options flag to collect

docs/cli.md, packages/cli/src/collect/collect.js, packages/cli/test/cli.test.js, packages/cli/test/collect.test.js, packages/cli/test/fixtures/autorun-start-server/autorun-server.js, packages/cli/test/test-utils.js, types/collect.d.ts
This PR introduces the changes to support custom listening pattern for `startServerCommand` through the new collect option `startServerReadyPattern`.
Closes https://github.com/GoogleChrome/lighthouse-ci/issues/134
=> feat(collect): support custom listening pattern for startServerCommand

README.md
The article explains exactly a use-case of Lighthouse CI for static site generators which can run a local server for serving files and test performance.
=> Add article reference for integration Lighthouse CI

packages/cli/src/collect/collect.js, packages/cli/src/collect/fallback-server.js, packages/cli/test/fallback-server.test.js, packages/cli/test/test-utils.js, types/collect.d.ts
Now we can't set both `startServerCommand` and `staticDistDir`. 
ref: https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/collect/collect.js#L100-L102
So server return 404 not found at sub-page in SPA.
I think `isSinglePageApplication` flag is very useful. (When using no SPA, 404 information is important)
Thanks.
closes https://github.com/GoogleChrome/lighthouse-ci/issues/157
=> feat(collect): Make it easy to use with SPA

packages/utils/src/build-context.js
I noticed lhci uses the last commit _that is not a merge commit_ when I ran in Gitlab CI. I think this behaviour is not desired because most CI providers set variables like `CIRCLE_SHA1` to the actual commit (even if it is a merge commit), so this creates inconsistencies between CI providers. This PR fixes two things:
- Read `CI_COMMIT_SHA` env variable to get the commit hash from Gitlab CI.
- When falling back to getting the hash form `git`, do not exclude merge commit so the hash is equal to that of any env variables. I also think this is better because people can still break something when resolving merge conflicts.
=> Allow use of merge commits in build hash; add Gitlab CI variable to get hash

docs/configuration.md, packages/cli/src/wizard/wizard.js, packages/cli/test/cli.test.js, packages/cli/test/fixtures/lighthouserc.json, packages/utils/src/lighthouserc.js, packages/utils/test/lighthouserc.test.js, types/lighthouserc.d.ts, types/wizard.d.ts
Hi,
i created the pr because we're running the `lhci server` behind a reverse proxy with authentication.
Now it's not possible to the the `lhci wizard` on a local machine because the wizard can't reach the server (missing authentication headers).
To fix that issue I changed the wizard command that a user can pass the `--config` argument (like autorun)
Example: 
`lhci wizard --config=./lighthouserc.json`
In the passed configuration it was now possible to set two different things:
- extraHeaders
- serverBaseUrl
The extraHeaders will be uses when the `lhci server` will be called.  
The serverBaseUrl can be used to set a default location for the remote `lhci server` address. 
Example configuration file: 
```javascript
{
"ci": {
"wizard": {
"serverBaseUrl": …
```
=> NEW add configuration argument to wizard command

docs/troubleshooting.md
Right now the current link takes to `v0.3.0-alpha.0` link where the file actually does not contain the section mentioned on the docs. This PR points the link to `master` where the section is present.
=> Fix link to lighthouserc on troubleshooting doc to point to master

docs/cli.md, packages/cli/src/upload/upload.js, packages/utils/src/build-context.js, packages/utils/test/build-context.test.js, types/upload.d.ts
closes #92 
@thedaviddias or anyone else with a github enterprise server would you be able to give this a try? I don't actually have access to a GH enterprise server to test for realz :)
=> feat(cli): support custom github API hosts

packages/cli/src/wizard/wizard.js, packages/cli/test/cli.test.js, packages/cli/test/fixtures/lighthouserc.json, packages/server/src/api/express-utils.js, packages/server/src/api/routes/projects.js, packages/server/src/api/storage/auth.js, packages/server/src/api/storage/sql/migrations/2020030501-admin-token.js, packages/server/src/api/storage/sql/project-model.js, packages/server/src/api/storage/sql/sql.js, packages/server/src/api/storage/storage-method.js, packages/server/test/server-test-suite.js, packages/utils/src/api-client.js, packages/utils/src/seed-data/dataset-generator.js, scripts/recreate-build.js, types/server.d.ts, types/wizard.d.ts
ref #85 
This PR:
- Adds the `adminToken` discussed in #85 to the project model
- Adds two authenticated routes protected by the admin token (DELETE of builds and projects)
- Adds a new wizard command for directly connecting to the SQL database to reset to a fresh admin token
Next steps:
- ~~Hash the admin token, never store in plaintext (required before merge)~~ DONE
- Add UI that allows a user to enter their admin token
- Add UI to delete builds/projects
~~still a WIP because this token is worth hashing compared to the public one, but pretty much~~ delivers o the server pieces of #85
=> Add basic admin auth to server API

docs/cli.md, packages/cli/src/collect/fallback-server.js, packages/cli/src/healthcheck/healthcheck.js, packages/cli/src/server/server.js, packages/cli/src/upload/upload.js, packages/cli/src/wizard/wizard.js, packages/cli/test/autorun-start-server.test.js, packages/cli/test/cli.test.js, packages/cli/test/test-utils.js, packages/cli/test/wizard.test.js, packages/server/package.json, packages/server/src/api/express-utils.js, packages/server/src/server.js, packages/server/test/basic-auth-server.test.js, packages/server/test/server-test-suite.js, packages/utils/src/api-client.js, scripts/test-lh-report.sh, types/server.d.ts, types/upload.d.ts, types/wizard.d.ts, yarn.lock
- adds optional HTTP Basic authentication to the server
- adds basic auth credential support to the healthcheck/upload/wizard CLI commands (can be used whether LHCI or a proxy implements basic auth)
- more tests for wizard and healthcheck flows around connecting to a server with options
**Sample Usage**
```
lhci server --basicAuth.password="LighthouseRocks"
lhci upload --basicAuth.password="LighthouseRocks"
```
closes #85 (for real this time 😄 )
=> Add HTTP Basic Authentication to server

packages/cli/src/assert/assert.js, packages/cli/test/autorun-start-server.test.js, packages/cli/test/autorun-static-dir.test.js, packages/cli/test/cli.test.js
The motivation is that when I had multiple URLs' results in the assertion dump...  I had a hard time figuring out if the "  16 result(s) for <url>" text was summarizing all the stuff above it, or providing a header of the stuff below it.
so i added a colon.
Also, I think formatting-wise it's a little clearer to indent the audittitle/docs. And i think we dont need the "documentation: " label.
---------
running the unit tests didnt really work for me.
I got a couple of these: 
and then many of the tests that were affected by these text changes werent run. i never saw failures. (i updated the snapshots by hand! 😨 )
i saw some other things too that I couldn't explain, but ... i'll leave it there for now. 
🤞 that the CI's tests run this with no problem! :)
=> fix(cli): tweak format of assertion results

packages/cli/src/healthcheck/healthcheck.js, packages/cli/test/autorun-start-server.test.js, packages/cli/test/cli.test.js, packages/utils/src/api-client.js, packages/utils/test/api-client.test.js
Will now fail autorun when trying to upload 0.3.x results to a 0.4.x server and viceversa.
ref #119
=> feat(cli): add API-version compatibility to healthcheck

docs/assertions.md, packages/utils/src/assertions.js, packages/utils/src/lodash.js, packages/utils/test/assertions.test.js, packages/utils/test/lodash.test.js
closes #279 
how does this API feel @WebCloud ?
The general format for asserting against a user timing value is `"user-timings:<kebab-cased-name>": ["<level>", {maxNumericValue: <value in milliseconds>}]`. For example, if you wanted to assert that a mark with name `My Custom Mark` started within the first 2s of page load and that a measure `my:custom-@-Measure` lasted fewer than 50 ms you would use the following assertions config.
Note that only the first matching entry with the name will be used from each run and the rest will be ignored.
```json
{
"assertions": {
"user-timings:my-custom-mark": ["warn", {"maxNumericValue": 2000}],
"user-timings:my-custom-measure": ["error", {"maxNumericValue": 50}]
}
}
```
=> feat(cli): add user-timing assertion support

packages/cli/src/healthcheck/healthcheck.js
This allows one to use the following example configuration:
```js
const puppeteer = require('puppeteer');
module.exports = {
ci: {
collect: {
settings: {
chromePath: puppeteer.executablePath(),
chromeFlags: ['--headless'],
},
url: ['https://google.com'],
},
},
};
```
=> Allow setting chromePath in collect settings

.travis.yml
trying something out to prevent CI from taking a full hour... 😐
https://travis-ci.org/github/GoogleChrome/lighthouse-ci/builds/677356728
=> chore: speedup mac travis runs

packages/cli/src/collect/collect.js, packages/cli/src/collect/puppeteer-manager.js, packages/cli/src/healthcheck/healthcheck.js, packages/cli/src/utils.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/healthcheck.test.js, packages/cli/test/test-utils.js
Followup to the work started in #282 , fixes an issue where `collect` would fail to even provide `--help` when no Chrome installations were found on Linux.
=> fix(cli): more consistent chromePath handling

docs/server.md
Fixes the image url for one of the screenshots in the LHCI server readme file.
=> docs(README): fix screenshot url

docs/getting-started.md
super important link and on my screen there's a wordwrap AND it is just small.
but its so important.
=> docs(getting-started): larger link text

docs/getting-started.md
I noticed this myself but then someone called it out and mentioned a nasty bug folks hit
https://github.com/paulirish/lite-youtube-embed/pull/55#discussion_r418314006
=> docs(getting-started): use checkout@v2

docs/cli.md
okay as you suggested this'll be slightly easier by commit.
a few extra things
* i added a TOC
* the _recopy with width 100_ commit has [a `git diff --word-diff` of this](https://user-images.githubusercontent.com/39191/80758775-068be300-8aeb-11ea-97a2-4511ab922c15.png).
* the `Configuration` section at the end is odd as it seems to duplicate what's already in the first paragraph under `Commands` and/or whats in the configuration.md.
=> docs(cli): tweaks, toc, reorder, global options

packages/cli/src/collect/collect.js, packages/cli/test/collect.test.js, packages/utils/src/saved-reports.js
ref #119 
DO NOT MERGE INTO MASTER, I'll be putting up a `next` branch to collect our breaking changes in case we need to publish fixes on 0.3.x in the meantime
BREAKING CHANGE: HTML reports in .lighthouseci/ will also be deleted on running of `collect`, not just the JSON
=> fix(cli): clear HTML reports on collect

README.md
fix extensions of introduction-to-ci.md in README.md.
=> docs(README): fix extension of introduction-to-ci.md

docs/configuration.md, packages/server/src/api/storage/sql/sql.js, types/server.d.ts
Adds the ability to provide advanced configuration options for Sequelize.
=> feat(server): support advanced sequelize options

docs/configuration.md, packages/cli/src/cli.js, packages/cli/src/upload/upload.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/upload.test.js, packages/utils/src/lodash.js, types/upload.d.ts
closes #142 
Basic usage: `lhci upload --target=filesystem --outputDir=./the-reports`
```
|- (cwd)
|- the-reports
|- manifest.json
|- www_example_com-_page-2020_05_22_21_15_05.report.json
|- www_example_com-_page-2020_05_22_21_15_05.report.html
```
```jsonc
[
{
"url": "https://www.example.com/page",
"isRepresentativeRun": true, // whether it's the median run
"htmlPath": "/path/to/cwd/the-reports/www_example_com-_page-2020_05_22_21_15_05.report.html",
"jsonPath": "/path/to/cwd/the-reports/www_example_com-_page-2020_05_22_21_15_05.report.json",
"summary": {"performance": 0.95, "seo": 0.9, "best-practices": 1}
}
]
```
=> feat(cli): add filesystem upload target

docs/recipes/docker-server/Dockerfile
We noticed that the image size could be greatly reduced by using
a smaller base image. This migrates the base image to `node:12-buster-slim`,
which provides the same functionality but shrinks the image size from
1.04GB to 286MB.
This also updates to the latest Node version 12.
=> Trim down Dockerfile

packages/utils/src/build-context.js
The issue I faced during not so standard implementation of lhci was error thrown by getAvatarUrl function. It stated that the app wasn't able to `determine commit email with ...`. and it made me look at LHCI_BUILD_CONTEXT__AUTHOR because that was the only place any email was mentioned. Only by looking at source code I saw that the env I was actually looking for was LHCI_BUILD_CONTEXT__AVATAR_URL, hence the better explanation in error's message.  Additionally, for every error that can be hardcoded with setting envs I've specified what env can be used to override it.
=> Make build context related errors more verbose.

docs/recipes/lhci-server-vpn-proxy/README.md, docs/recipes/lhci-server-vpn-proxy/nginx.conf, docs/server.md
Fixes: https://github.com/GoogleChrome/lighthouse-ci/issues/352
Fixes: #308
Based on the following lhrc config:
```
{
ci: {
upload: {
target: 'lhci',
serverBaseUrl: 'https://custom-server.com/lighthouse',
token: TOKEN,
basicAuth: {
username,
password
}
}
}
}
```
`_normalizeUrl` resolves to origin url set by `serverBaseUrl`, not the desired `serverBaseUrl` as set:
`https://custom-server.com`
I propose that the `serverBaseUrl` for client CLI config is always used when the target is `lhci`. If someone wants `domain.com/path/to/server` then it should honor that, not use `domain.com`
Always resolve relative to `serverBaseUrl` not the origin:
`https://custom-server.com/lighthouse`
=> [RFC] Fix base url issue where the wrong origin is used

packages/server/src/ui/routes/project-dashboard/graphs/category-score/category-score-graph.css, packages/server/src/ui/routes/project-dashboard/graphs/category-score/category-score-graph.jsx
Fixes #357
Make it clearer that you MUST click on the graph dot for the popup to be "pinned" or "suspended" for further action (ie clicking "Report").
=> Add info tip to category score popup

docs/recipes/docker-client/README.md
Related to https://github.com/GoogleChrome/lighthouse/issues/9307
lighthouse fails to get results of heavy content pages if chrome has limited docker shared memory.
Using --shm-size=2g fixes this issue.
Another advice about using --cpus to control the CPU available to the lighthouse. 
I also want to include advice to run a single test at a time on a dedicated machine to ensure equal CPU cycle availability between tests. This leads to the most consistent results but this seems infeasible in most cases. Scenarios like web.dev and page speed insight will have exponential hardware costs if they go this way. We are doing this at housing.com which has limited resource requirements. Please advice.
=> document --shm-size and --cpus for consistent results

docs/recipes/docker-client/Dockerfile, packages/cli/src/upload/upload.js, packages/utils/src/build-context.js
fixes #370 , typescript believes this to be an impossibility and ~~I'm also not sure how to reproduce it either~~ It's only reproducible when git is not installed, so no tests, but seems like a reasonable safeguard to have
=> fix(utils): better error message for git failures

docs/configuration.md, packages/server/src/api/storage/sql/sql.js, packages/server/test/mysql-socket-path-server.test.js, packages/server/test/postgres-socket-path-server.test.js, types/server.d.ts
Fixes https://github.com/GoogleChrome/lighthouse-ci/issues/385
As mentioned in the ticket, my team and I were looking to set up lighthouse-ci server on Google Cloud Run (serverless containers) with a Google Cloud SQL database (Postgres) and our only possibility to link the two was to use a socket path instead of a connection URL.
Let me know what you think of this config, there's probably a few things that still need to be done or validated in terms of how you want the config to look like.
Also @patrickhulce mentioned that testing might be quite hard for this one, so I'm looking for any proposal on how I could tackle this 😄
=> feat(server): support socket path in server config

docs/configuration.md, packages/cli/src/autorun/autorun.js
By default, Next.js builds to the folder `out` when the command `next export` is used. I can't think of an alternate use for the out directory beyond builds, so I think it would be useful if this is one of the defaults.
=> Add config for Next.js

packages/cli/src/upload/upload.js, packages/cli/test/autorun-static-dir.test.js
=> feat(cli): log attempts to save url map

docs/configuration.md
The current documentation lists only `"lhci", "temporary-public-storage"``as targets, however it seems that "filesystem" is also an option. This pull request adds it to the list.
=> Update "target" configuration documentation

docs/configuration.md
Resolves https://github.com/GoogleChrome/lighthouse-ci/issues/430
=> docs(configuration): Add desktop docs

packages/cli/package.json, yarn.lock
Update `chrome-launcher`.
`chrome-launcher@0.12.0` now carries the risk of command injection. `@lhci/cli` should use `> 0.13.1`.
I updated to the latest version.
Ref: https://github.com/GoogleChrome/chrome-launcher/pull/197
=> fix(cli): bump chrome-launcher from 0.12.0 to 0.13.4

docs/configuration.md
Under the covers, it seems that the value of `sqlConnectionUrl` is passed through to Sequelize, so we should be more clear about what's allowed in the format of that string.  Relevant Sequelize documentation on the proper format can be seen here:  https://sequelize.org/v4/manual/installation/getting-started.html#setting-up-a-connection.
=> Update Docs on SQL Connection URL Format

docs/configuration.md, packages/utils/src/build-context.js, packages/utils/test/build-context.test.js
Adds `LHCI_BUILD_CONTEXT__AUTHOR_EMAIL` environment variable to override getting the commit author's email from git, and uses this to get the gravatar URL when `LHCI_BUILD_CONTEXT__AVATAR_URL` is not specified.
Resolves #446
=> feat(utils): add build context env for author email (#446)

docs/configuration.md
I spun this up for testing my own config and thought it might he helpful for others.
=> docs: link to online REPL for testing `urlReplacementPatterns`

docs/configuration.md, packages/cli/src/collect/collect.js, packages/cli/test/collect-puppeteer.test.js, packages/cli/test/collect-static-dir.test.js, types/collect.d.ts
This PR allows you to filter out certain URLs that you would like to be skipped over during testing. This is used alongside staticDistDir and is not functional with url (Not sure how exactly that would end up working).
=> Add flag to filter out URLs you don't want to be tested

packages/server/src/api/storage/sql/sql.js, packages/server/src/api/storage/storage-method.js, packages/server/src/cron/delete-old-builds.js, packages/server/src/cron/psi-collect.js, packages/server/src/cron/utils.js, packages/server/src/server.js, packages/server/test/cron/delete-old-builds.test.js, packages/server/test/cron/utils.test.js, types/collect.d.ts, types/server.d.ts
I add cron task that delete old builds on sql to the server.
fixes: https://github.com/GoogleChrome/lighthouse-ci/issues/463
=> feat(server): Server should periodically delete old builds

README.md, docs/complex-setup.md, docs/getting-started.md
I fixed document to fit current version.
I think it would be used `latest`.
```
npm install -g @lhci/cli@latest
```
=> docs: bump lhci from 0.4.x to 0.5.x

packages/cli/src/collect/node-runner.js, packages/cli/test/autorun-static-dir.test.js, packages/cli/test/collect-static-dir.test.js, packages/cli/test/test-utils.js
=> tests(cli): add mock LHR support

packages/utils/src/assertions.js, packages/utils/test/assertions.test.js
Some audits will not have a `.details.items` array at all when they pass, even though they support `.details.items` so Lighthouse CI needs to support this case.
fixes https://github.com/GoogleChrome/lighthouse-ci/issues/481
=> fix(utils): handle missing details.items

package.json, yarn.lock
fixes: https://github.com/GoogleChrome/lighthouse-ci/issues/488
`yarn install` failed on Ubuntu:20.04 if `which python` returns nothing.
I think `sqlite3` should be updated.
```bash
$ docker run --rm -it ubuntu:20.04
root:/# apt update
root:/# apt install build-essential git curl -y
root:/# curl -Ls "https://nodejs.org/dist/v14.15.0/node-v14.15.0-linux-x64.tar.gz" -o "node-v14.15.0-linux-x64.tar.gz"
root:/# tar -C /usr/local --strip-components 1 -xzf node-v14.15.0-linux-x64.tar.gz
root:/# npm install -g yarn
root:/# git clone https://github.com/GoogleChrome/lighthouse-ci.git
root:/# apt install python2
root:/# cd lighthouse-ci
root:/# yarn upgrade sqlite3@latest  
root:/# update-alternatives --install /usr/bin/python python /usr/bin/python2 1
root:/lighthouse-ci# yarn install
```
=> bump sqlite3 from 4.2 to 5.0

packages/server/src/ui/layout/page-sidebar.css, packages/server/src/ui/routes/project-list/project-list.css
The project list was hidden from view when I registered a lot of projects.
I fixed scrollable.
before
after
=> feat: scrollable project list

.github/workflows/ci.yml
ref https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> chore(ci): remove usage of set-env

docs/getting-started.md, docs/introduction-to-ci.md
Thought it'd be good to add in Google Cloudbuild. I've also upgraded the referred image on GitLab as that image doesn't seem to work with Lighthouse 6.
We're running on HIGHCPU_32 as it delivers the best and most consistent results (and HIGHCPU_8) is similar to Github Actions which doesn't return consistent results.
=> Adding in Cloudbuild documentation

packages/cli/package.json, packages/cli/src/collect/node-runner.js, packages/server/package.json, yarn.lock
Fix #500 by using a more robust random filename generation
=> Fix #500 by using uuid to generate the random filename

docs/recipes/docker-server/kubernetes/lhci-deployment.yml, packages/server/src/server.js, packages/server/test/basic-auth-server.test.js, packages/server/test/server-test-suite.js
Google Kubernetes Engine default ingress requires a health check route that returns a 200 response. If basic authentication is enabled, there is no route that can be used for a health check. This PR adds a `/healthz` route before the auth middleware to be used for health checks.
=> feat(server): add a health check route before auth

packages/cli/package.json, packages/utils/package.json
When installing `@lhci/cli`, npm show us "4 low severity vulnerabilities" : 
We should not use dependencies with vulnerabilities.
In the future to avoid these sort of things, we could use [dependabot](https://dependabot.com/), it is a builtin solution in GitHub to automatically update dependencies.
**Link about the vulnerabilities :**
- https://www.npmjs.com/advisories/1500/versions
- https://www.npmjs.com/advisories/1556
**What changes this PR introduce ?**
- Bump `isomorphic-fetch` from 2.2.1 to 3.0.0
See: https://github.com/matthew-andrews/isomorphic-fetch/issues/192
The only things to be aware by doing this upgrade : "Node.js 0.10.x and 0.12.x support is dropped"
- Bump `yargs` from 12.0.5 to 15.4.1
Didn't check what need to change in the codebase to support the latest version of …
=> build(deps-cli): fix npm vulnerabilities

.gitignore, docs/configuration.md, packages/server/src/cron/delete-old-builds.js, packages/server/test/cron/delete-old-builds.test.js, types/server.d.ts
Sometimes it would be extremely helpful to have some additional configuration options to describe logic, like:
I want to keep master builds for a year and all other branches for a short period of time
=> feat(server) add ability to configure multiple cron tasks and specify which branches should be excluded or included during deletion.

packages/utils/src/build-context.js
Additional support for build context environment variables provided by GitLab
See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
=> feat(utils): more gitlab build context support

docs/getting-started.md
Users copy-pasting the existing starting template will run into issues such as https://github.com/GoogleChrome/lighthouse/issues/11953, since lighthouse CI will not work with node 10.
=> reference node 12 as supported version

packages/server/src/api/storage/sql/sql.js, packages/server/src/server.js
improves the debug logging and rejection behavior when the LHCI server fails to start
=> fix(server): reject on server initialization errors

docs/configuration.md, packages/cli/src/server/server.js, packages/server/src/server.js, types/server.d.ts
This PR adds the ability to pass a listening host to the Lighthouse CI server.
This makes it possible to let it bind to localhost or IPv4 with `0.0.0.0`.
**Background**
We want to run the docker image in our Kubernetes cluster. 
So we create a deployment with the `patrickhulce/lhci-server` image.
When accessing the server via the nginx ingress we keep getting a http 503 error.
After investigation the problem seems to be that the service is listening on IPv6 instead of IPv4.
So if we could pass it a IPv4 listenhost of `0.0.0.0` the server will use IPv4 instead of IPv6 and the problem will be solved.
Output netstat:
```
root@lhci-server-7fdf98f947-l8dwg:/usr/src/lhci# apt-get update && apt install -y net-tools
root@lhci-server-7fdf98f947-l8dwg:/usr/src/lhci# netstat -tulpn | grep LISTEN …
```
=> feat(server): enable passing of server host

docs/getting-started.md
Previous setup script referenced Node 10 which will fail to run with the latest version of `@lhci/cli`.
This is a quick update for those who may also run across this :+1: 
fixes #591
=> docs(jenkins): update Node version to 12 for setup script

packages/cli/src/autorun/autorun.js, packages/cli/src/upload/upload.js, packages/cli/test/autorun-github.test.js, packages/cli/test/fixtures/autorun-github/build/bad.html, packages/cli/test/fixtures/autorun-github/build/good.html, packages/cli/test/fixtures/autorun-github/lighthouserc.json, packages/cli/test/fixtures/autorun-github/mock-github-server.js
Related to #575 
Just getting it over the line (hopefully)
Took inspiration from the psi tests and set a mock server for github status check.
=> fix(cli/upload): Fix GitHub status check

docs/configuration.md
Found out that when using certificates defined else where you need to specify in the `sqlDialectOptions` that ssl is true.
Related thread - https://github.com/sequelize/sequelize/issues/956#issuecomment-147745033
Just felt it should be noted in the docs.
I suppose the alternative is to bind `sqlConnectionSsl: true` to map to
```
dialectOptions: {
ssl: true,
}
```
Without this the API returns:
```
SequelizeConnectionError: no pg_hba.conf entry for host "172.18.48.124", user "lighthouseci", database "lighthouseci", SSL off
   at /usr/src/lhci/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:24
   at Connection.connectingErrorHandler (/usr/src/lhci/node_modules/pg/lib/client.js:194:14)
   at Connection.emit (events.js:315:20)
   at Socket.<anonymous> …
```
=> docs(server): SQL SSL docs update on using ssl with no custom cert

packages/cli/src/healthcheck/healthcheck.js, packages/cli/test/autorun-start-server.test.js, packages/cli/test/cli.test.js
Based on the thread in the attached ticket, I've clarified the debug messages when LHCI checks commit hash uniqueness.
Close #612
=> Update debug messages when checking hash uniqueness

packages/cli/src/open/open.js
- `lhci open` command currently silently fails if configuration `ci.collect.url` is an array of URLs (valid) rather than a string
1. Set configuration:
```
ci: {
collect: {
url: [
'https://www.google.com/',
'https://www.google.de/'
]
}
}
```
2. Run `lhci collect` to generate reports successfully
3. Run `lhci open`. No URL opened in browser (due to `continue`) but `Done!` message still printed to console
=> fix(cli): lhci open to process multiple urls

docs/complex-setup.md, docs/getting-started.md, docs/server.md
While doing the first time set-up I noticed that the getting started docs are not up-to date with the current CLI version so I updated all `npm install` commands to 0.8.
Also I noticed that the migration guide doesn't include guidance on 0.7 to 0.8 yet. Maybe you can add those?
=> update cli version to 0.8 in docs

docs/configuration.md
=> Fix readability on configuration.md

docs/troubleshooting.md
When running LHCI in GH Actions due to how checkout action clones the repo with a fetch depth of 1 by default the base branch might be missing so LH will not be able to find it during health check.
Changing the action settings and fetching the base using a new step will fix this problem for almost all cases where the repo is big enough.
This has been discussed here https://github.com/actions/checkout/issues/93 and here https://github.com/actions/checkout/pull/213
=> Add additional troubleshooting entry for Ancestor hash not determinable

packages/server/package.json, packages/server/src/ui/components/lhr-viewer-link.jsx, packages/server/src/ui/entry.jsx, packages/server/src/ui/index.html, packages/viewer/package.json, packages/viewer/src/ui/entry.jsx, packages/viewer/src/ui/index.html, yarn.lock
As discussed in https://github.com/GoogleChrome/lighthouse-ci/discussions/635 - this provides two relatively simple changes:
- Makes use of fontsource to pull in roboto, roboto-mono, and material icons instead of using the googleapis font CDN (without use of a proxy these lead to rendering issues on the server-ui and viewer)
- An optional use of $VIEWER_ORIGIN environment variable to configure a self-hosted [viewer](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-viewer) instead of linking to the public internet copy on github
As I mentioned in the discussion, I have relatively little UI experience and if there's a better way to accomplish these localizations I'm open to learning other options. I think the alternative I was finding a lot of while googling was using …
=> Updates to support closed network

packages/utils/src/lighthouserc.js, packages/utils/test/lighthouserc.test.js
This allows users to use Lighthouse CI in a project which has `"type": "module"` in their `package.json` file.
I also looked into supporting ESM configuration files, but since `import()` is asynchronous, this is a lot more work than just supporting `.cjs` files in a code base I’m not very familiar with.
=> feat: support cjs config file extension

README.md
The latest release of Lighthouse is not reflected in the `Getting started` section of the README. This change updates the version.
=> docs: update readme to use 0.8.x

README.md
Specify node.js version for `actions/setup-node@v1` step in example Github Actions code. Without this, the snippet [currently fails](https://gist.github.com/j0nas/06fc18b10d74d9b8ca3ad8f0db9cac74) as it defaults to an earlier version of node.js which raises a SyntaxError for the current version of the module.
=> Specify node.js version in Github Actions example

packages/server/src/ui/routes/project-dashboard/category-card.jsx
This PR will allow users to see LCP, TBT, and FIB in distribution graphs on the dashboard.
=> Add LCP, TBT and FID to Distribution Graph

docs/configuration.md, packages/server/src/cron/psi-collect.js, packages/server/test/cron/psi-collect.test.js, packages/utils/src/psi-client.js, packages/utils/src/psi-runner.js, packages/utils/test/psi-client.test.js, types/server.d.ts
=> Allow for further configuration of psiCollectCron

packages/server/package.json, scripts/build-app.js
=> fix(viewer): use correct publicPath, replace process.env

docs/recipes/docker-client/Dockerfile, docs/recipes/docker-server/Dockerfile
Also had to download some build tools to get the server dockerfile to build. It was failing to find a prebuilt sqlite binary for the node+sqlite version, so has to build from source.
=> update dockerfiles to use node 14

package.json, packages/server/src/server.js, packages/server/src/ui/index.html, packages/viewer/src/ui/app.jsx, packages/viewer/src/ui/index.html, scripts/build-app.js, yarn.lock
https://googlechrome.github.io/lighthouse-ci/viewer/ is busted
fixes #767
but if you build locally and run your server from inside /packages/viewer/dist its all good. the problem is some root-absolute urls... eg `<script src="/script-needed-from-origin-root.js">`
anyhow. This appears to be the sleekest solution that keeps both viewer and the server app looking good with no broken references.
i found a lot of weird behavior regarding `@chialab/esbuild-plugin-html'` and `entryNames`, `assetNames` and `chunkNames`. really weird. [filed this one](https://github.com/chialab/rna/issues/49).
but.. ultimately this new usage of that module feels like an improvement over the current status quo. 
<details>
<summary>some development notes</summary>
of course the root problem is plenty of 404s.
this …
=> fix standalone viewer build via build-app adjustments

docs/getting-started.md
Found this typo while reading the docs.
=> docs: s/enviroment/environment

packages/utils/src/assertions.js, types/assert.d.ts
Moves the type definitions of assertions into the main declaration file, under the `LHCI.AssertResults` namespace.
This allows the output JSON file to have an expected type. This is especially useful in Deno, where you can do:
```ts
// With a version number that’s not actually v0.9.0
import "https://raw.githubusercontent.com/GoogleChrome/lighthouse-ci/v0.9.0/types/assert.d.ts";
const results: LHCI.AssertResults.AssertionResult[] = JSON.parse(
Deno.readTextFileSync(`.lighthouseci/assertion-results.json`)
);
```
=> feat: extract type defs to assert.d.ts

packages/cli/src/upload/upload.js, packages/cli/test/upload-url-hash.test.js
- `hash` parameter, while generating reports for apps using #/ 
- Test case added for the same
- This change is in reference to [this](https://github.com/GoogleChrome/lighthouse-ci/discussions/834) thread, as per discussion with @patrickhulce.
=> feat(cli): Added url hash to differentiate between urls

.github/workflows/ci.yml, package.json, packages/cli/test/cli.test.js, packages/cli/test/healthcheck.test.js, yarn.lock
- `@chialab/esbuild-plugin-html` needed to be bumped to fix a problem with paths on windows. Otherwise, the server did not build correctly.
- `./script.js` is bad form on Windows, using `node ./script.js` now
=> tests: fix windows unit tests

packages/server/package.json, packages/viewer/package.json, packages/viewer/src/ui/index.html, scripts/build-app.js, scripts/source-map-explorer.sh, tsconfig.json
Fixes #875 
Basically a continuation from last year's https://github.com/GoogleChrome/lighthouse-ci/pull/753 and more specifically https://github.com/GoogleChrome/lighthouse-ci/pull/786
The short version is... esbuild consuming HTML and css is rough. Parcel treated us well.
in 786 we fixed static serving (the viewer) but made sure the express-based serving (the server) still worked.
it did until it didnt. maybe [some dependency bumps](https://github.com/GoogleChrome/lighthouse-ci/issues/875#issuecomment-1440254536)?  shrug.
But...... this works. 
I spent a bunch of time making a more generalized solution. I ended up for something sliiiiightly more specific, but I'm still happy with it.
oh.. and just like in https://github.com/GoogleChrome/lighthouse-ci/pull/786 ... 
<details> …
=> Fix static subresource paths for server/viewer

.github/workflows/ci.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Updated workflows to cache dependencies using [actions/setup-node](https://github.com/actions/setup-node#caching-global-packages-data). `setup-node@v3` or newer has caching **built-in**.
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.
Node.js projects can run faster on GitHub Actions by enabling dependency caching on the [setup-node](https://github.com/actions/setup-node) action.
```yaml
- name: Use Node.js 16.x
uses: actions/setup-node@v1
with:
node-version: 16.x
- run: yarn …
```
=> misc: use cache in ci.yml

docs/server.md, packages/server/src/server.js, types/server.d.ts
Hi thanks for this project 😄 
This PR allows to use **fastify** in custom middleware. Without this PR you cannot wrap this express server due to **bodyParser**
=> feat(server): allow suppressing bodyParser to use own middleware

packages/cli/src/autorun/autorun.js
Hey 👋🏻 
I was surprised when Lighthouse CI didn't detect my built page when setting up a new build. The error message was really helpful, so I got up and running quickly, but I figured I'd ask if you'd consider adding `_site` to the list of automatically detect `staticDistDir` directories.
I figured that it would be a low-risk change, since I suspect that there aren't many directories named `_site` in other systems.
Let me know what you think :)
https://www.11ty.dev/docs/config/#output-directory
=> detect 11ty's output dir as `staticDistDir`

docs/recipes/docker-client/Dockerfile
A while ago I submitted https://github.com/GoogleChrome/lighthouse-ci/pull/736 to fix issues with using puppeteer in the lhci-client docker image. 
In the meantime, puppeteer seems broken again in the latest docker image version. After some investigation, this is most likely a problem occurring after the puppeteer upgrade from v13 to v19. In more recent versions, puppeteer [keeps a cache of browser versions it downloads](https://pptr.dev/guides/configuration#examples). Since in this image we skip the chromium download for puppeteer, because a chrome version is already included for the ligthouse tests, we should specify where our chrome version is located. This was quick fixable by passing the env var in the `docker conatiner run` command, but should in my opinion be defined in the …
=> fix(docker): added extra environment variable to lhci-client Dockerfile for puppeteer executable

README.md, docs/complex-setup.md, docs/getting-started.md
Yo! Figured this should be updated since we're on version 0.12 now.
=> Instruct users to install Lighthouse CI 0.12

packages/viewer/src/ui/app.jsx
Issue: #935 
We add a try/catch to catch the error, but keep the application running. We show a console.log with the captured error.
=> catch localStorage exceptions in difftool

docs/configuration.md
=> docs: fix typo of puppeterScript to puppeteerScript

package.json
There are a few tests that I suspect squash each other when run in parallel. The previous value here set max to 2 (probably because the longest test by far - storybook - is not impacted), but that could still result in a problem.
ref #981
=> chore: set jest max workers to 1

packages/cli/src/assert/assert.js, packages/utils/src/saved-reports.js, types/assert.d.ts
ref https://github.com/GoogleChrome/lighthouse/issues/15203
Enables usage like this:
```
node packages/cli/src/cli.js -no-lighthouserc assert \
--lhr /Users/cjamcl/src/lighthouse/core/test/results/sample_v2.json \
--budgetsFile=packages/cli/test/fixtures/budgets.json
```
=> feat(cli): add --lhr to assert command to load LHRs from anywhere

README.md
Adding a new github action that can be used to compare the Lighthouse CI current commit build versus the Ancestor build.
=> docs: added actions-lighthouseci-compare
